### ISSUE TITLE
CHROME OS NOT OPENING

### ISSUE THREAD

**Issue by circle-symbol** [PreMiD/Linux#100]
PreMiD chrome os not opening

**Comment by faultydev** [comment]
Afaik, chrome OS' linux runs in a sandbox.. meaning no PreMiD support.
If I'm wrong correct me but if you turn on [developer mode](https://www.xda-developers.com/how-to-turn-on-chrome-os-developer-mode/), it *should* work.

**Comment by Bas950** [comment]
We do not support ChromeOS atm.

**Comment by Prince-Noctis-XV** [comment]
It's running on my Chrome Os though lol
