### ISSUE TITLE
PackageCloud repo install doesn't work on Ubuntu. (README.md)

### ISSUE THREAD

**Issue by slash1div** [PreMiD/Linux#105]
My Ubuntu version is 21.10, however, this also happens to LTS. 
Something like this may also happen to Debian.

After running the repo install script found on line 125 of [README.md](https://github.com/PreMiD/Linux/blob/master/README.md?plain=1#L125), running ``sudo apt install premid`` returns that there isn't a package named premid.

To fix this, add a different repo install command for Ubuntu.
```bash
curl -s https://packagecloud.io/install/repositories/PreMiD/Linux/script.deb.sh | sudo os=Ubuntu dist=hirsute bash
sudo apt install premid
```

**Comment by alexbcberio** [comment]
Thank you for the suggestion, I have updated the readme with clear instructions about the procedure
