### ISSUE TITLE
ChromeOS Support

### ISSUE THREAD

**Issue by doomlerd** [PreMiD/Linux#11]
Support is not guaranteed to ever happen but there will be a try soon, any help with ways to install it and still not ruin the OS will be appreciated.

**Comment by Jonyk56** [comment]
I would love to see this implemented immediately, this is something i know more than 100 thousand people would love to see asap!

**Comment by Sea-deb** [comment]
This is a way that you can use PreMiD through ChromeOS but i don't advise it for people who have old laptops cause it's to laggy.

1. Download the Chrome version of linux : https://www.google.com/chrome/

2.Download PreMiD extension Through the chrome you just downloaded.

3. Run This in the terminal `wget https://github.com/PreMiD/Linux/releases/latest/download/PreMiD-Portable.AppImage && chmod a+x PreMiD*.AppImage
`
4. After that Run `./PreMiD*.AppImage`

It's just like the usual way to download PreMiD Just so you know.

I hope this helps for people who wanna download PreMiD in there chromebook

**Comment by XCoderever** [comment]
> This is a way that you can use PreMiD through ChromeOS but i don't advise it for people who have old laptops cause it's to laggy.
> 
> 1. Download the Chrome version of linux : https://www.google.com/chrome/
> 
> [2.Download](http://2.Download) PreMiD extension Through the chrome you just downloaded.
> 
> 1. Run This in the terminal
>    `wget https://github.com/PreMiD/Linux/releases/latest/download/PreMiD-Portable.AppImage && chmod a+x PreMiD*.AppImage `
> 2. After that Run
>    `./PreMiD*.AppImage`
> 
> It's just like the usual way to download PreMiD Just so you know.
> 
> I hope this helps for people who wanna download PreMiD in their chromebook.

kinda dangerous... it might break it...

**Comment by doomlerd** [comment]
Just for your information guys, I may need some help with testing soon as this is still in progress
will keep you updated.

**Comment by ririxichan** [comment]
PreMiD with v3 update should support chromeOS. For now I'm closing this issue and pinning it.
