### ISSUE TITLE
Chrome sandbox must be owned by root and mode 4755 on linux

### ISSUE THREAD

**Issue by danbulant** [PreMiD/Linux#16]
**Describe the bug**
Running the app will result in error about chrome-sandbox (probably because of electron), but it can't be fixed as the directory is always generated and doesn't persist.

**To Reproduce**
1. Download latest PreMiD from downloads
2. Run it

**Expected behavior**
Either normally running application, or ask for sudo at startup.

**Screenshots**
```
[7514:0402/100824.292785:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_PreMiDQC5vcq/chrome-sandbox is owned by root and has mode 4755.
[1]    7514 trace trap  ./PreMiD-Portable.AppImage
```

**Desktop (please complete the following information):**
 - OS: Linux Debian Buster
 - Browser: Chrome
 - Version: 2.2.15

**Additional context**
This is a linux only bug, as sandbox doesn't require those rights on Windows and MacOS. This is specific to chromium, but since you're probably using electron in the PreMiD, it's standart.

**Comment by doomlerd** [comment]
Issue fixed in : 
- [ ] AppImage
- [x] DEB file
- [ ] RPM file
- [ ] AUR
- [ ] Tarball ( fixes AUR as well )

**Comment by doomlerd** [comment]
We're currently moving away from Electron, there won't be a need to resolve this anymore.
