### ISSUE TITLE
Adding a inverted color icon.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [PreMiD/Linux#5]
_[Port of my issue from the previous repository.](https://github.com/doomlerd/PreMiD-Linux/issues/13#issue-577308330)_

**Is your feature request related to a problem? Please describe.**
The PreMid application, has only a white icon, making it fade easily in the notification tray for those having a clear bright dock.

![](https://user-images.githubusercontent.com/13170204/76140601-82722d80-605c-11ea-8b31-eb895aef43e8.png)
![](https://camo.githubusercontent.com/827c7a72aad8b62881c70da78ac56ca13b18ec00/68747470733a2f2f6672616d617069632e6f72672f6c4b596a69574938555a5a392f794574673041664c706431792e676966)
_Demonstrated on the ZorinOS GNOME dock._
**Describe the solution you'd like**
Have either an option, to switch to a colored icon, which should help to contrast more on the notification tray.
![](https://camo.githubusercontent.com/d75573908b029dbb75f5b2ba3a7dc7aa6a8fa1e0/68747470733a2f2f6672616d617069632e6f72672f4f3650674a4372527356374f2f384f5479506157376e6231372e676966)
_Demonstrated with the [ckb-next](https://github.com/ckb-next/ckb-next) application_
Or better, having a bright and dark icon switch in the settings.
![](https://camo.githubusercontent.com/2aaad36d55e6640062cefe0a3f833debf8386da2/68747470733a2f2f6672616d617069632e6f72672f6a696c496a384339627234332f52325176527655355a78434f2e676966)
_Demonstrated with the [Habits](https://github.com/atareao/habits) application._

**Comment by doomlerd** [comment]
Would having a tiny black outline to it solve the problem? ( same as the Discord icon )

**Comment by PoorPocketsMcNewHold** [comment]
> Would having a tiny black outline to it solve the problem? ( same as the Discord icon )
I suppose, The difference being that the Discord icon in itself, is not exactly pure white as the notification tray is.
But this should work as well.

**Comment by doomlerd** [comment]
We're currently moving away from Electron, there won't be a need to resolve this anymore
If anyone is interested in adding a systray icon, feel free to do so after the update is pushed.
(work on the inverted icon itself is in progress but there won't be a way to use it, at least not now)
