### ISSUE TITLE
The PreMiD installation script doesn't work for openSUSE based distros (RPM)

### ISSUE THREAD

**Issue by LothaireCliquennois** [PreMiD/Linux#81]
**Describe the bug**

Not exactly a bug, it's just that the script doesn't work as-is for openSUSE (for the fixed or rolling release version) based distributions.

**To Reproduce**
1. Use an Linux distro that has openSUSE's repos, like openSUSE Leap/Tumbleweed or Gecko Linux for example
2. Install the script with the command
3. Do a ```zypper in premid``` after a ```zypper update``` or a ```zypper dup```

**Expected behavior**
Getting PreMiD to actually install from the repositories/overlays/recipes as on most distros I tried in my life.

**Screenshots**
The only thing I could show is the emptyness of YaST, Discover, or zypper when I search for PreMiD.

**Desktop:**

- OS: openSUSE based distros, should be the same with every single DEs, versions and kernels.
- Browser : not a browser related issue (or so do I think)
- Version : not applicable

**Additional context**
I'd like to NOT be resigned to use the .AppImage file if that makes any sense...
Plus that should not be an issue as when I launch the script, it recognizes "openSUSE/version".
Since the distro follows the lsb_release standard.

**Comment by ririxidev** [comment]
Because I didn't add openSUSE version to our packagecloud. Just change settings like script says or download .rpm file yourself from uploaded ones. I will add opensuse later.
