### ISSUE TITLE
Presence Buttons Support for PreMiD Linux

### ISSUE THREAD

**Issue by v30xy** [PreMiD/Linux#87]
**Is your feature request related to a problem? Please describe.**
I'm making my first PreMiD Presence and i added the new buttons feature but PreMiD Linux app does not support buttons so not working.

**Describe the solution you'd like**
Presence buttons update for PreMiD Linux.

**Comment by Bas950** [comment]
Linux already has support for Buttons, or you are using an older version or you did something wrong in your presence.

**Comment by v30xy** [comment]
> Linux already has support for Buttons, or you are using an older version or you did something wrong in your presence.

Installed from [here](https://packagecloud.io/PreMiD/Linux). Latest build 24 days ago. I tried several time but buttons never worked. After i cloned original repo and started, buttons worked.

**Comment by Bas950** [comment]
Yikes yea its an error on our side, will fix in a sec lmao
(Forgot to update yarn.lock)

**Comment by ririxidev** [comment]
Heya! Could you try 2.3.2 version and see if that works? Thanks!

**Comment by Bas950** [comment]
![image](https://user-images.githubusercontent.com/34792838/111234237-6483c500-85ee-11eb-9c95-a29330f6b710.png)
Working now!
