### ISSUE TITLE
PackageCloud doesn't have a release file

### ISSUE THREAD

**Issue by DashCruft** [PreMiD/Linux#91]
**Describe the bug**
PackageCloud has problems for Linux based OS

**To Reproduce**
1. Run this inside of ur debian console:
`curl -s https://packagecloud.io/install/repositories/PreMiD/Linux/script.deb.sh | sudo bash`
2. `sudo apt update`
3. The error will show up.

**Expected behavior**
Doesn't include any error while updating using `sudo apt update` 

**Screenshots**
![image](https://user-images.githubusercontent.com/59381835/114108982-209c7c80-9889-11eb-8fe5-8c8aee94bdaa.png)

**Desktop:**
- OS: Kubuntu 20.10 
- Browser: Brave
- Version: Latest

**Additional context**
This might have something to do with the newest ubuntu update which is 20.04 and higher.

**Comment by ririxidev** [comment]
Yeah um, package doesn't exist on ``ubuntu/groovy`` because it isn't uploaded. Didn't really know that there is new version. I will upload it when I will have time for this package.

**Comment by ririxidev** [comment]
Added [https://packagecloud.io/PreMiD/Linux/packages/ubuntu/groovy/premid_2.3.2_amd64.deb](packagecloud.io/PreMiD/Linux/packages/ubuntu/groovy/premid_2.3.2_amd64.deb).
