### ISSUE TITLE
Unable to downloads repo

### ISSUE THREAD

**Issue by Firefox289** [PreMiD/Linux#94]
Unable to download repo config from: https://packagecloud.io/install/repositories/PreMiD/Linux/config_file.list?os=Pop&dist=focal&source=script

This usually happens if your operating system is not supported by
packagecloud.io, or this script's OS detection failed.

You can override the OS detection by setting os= and dist= prior to running this script.
You can find a list of supported OSes and distributions on our website: https://packagecloud.io/docs#os_distro_version

For example, to force Ubuntu Trusty: os=ubuntu dist=trusty ./script.sh

If you are running a supported OS, please email support@packagecloud.io and report this.

i get this error when i ruen the curl command running pop os

**Comment by ririxidev** [comment]
If you want to download it on PopOS just force other distro that is supported.
